name: "FAP: Build"

on: [push]

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: 'ufbt: Build'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app
        with:
          sdk-channel: release

      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
