name: "FAP: Build"

on: [push, workflow_dispatch]

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: release channel
            sdk-channel: release
          - name: RC channel
            sdk-channel: rc
          - name: dev channel
            sdk-channel: dev

    name: "ufbt: Build for ${{ matrix.name }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-channel }}

      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
